### PR TITLE
Make documentation

### PR DESCRIPTION
**Pull request by mdpiper**
This PR adds user and API documentation, written with Sphinx, for the *babelizer*.  

Todo:

- [x] Write a long-form example of wrapping [bmi-example-c](https://github.com/csdms/bmi-example-c)
- [x] Build the docs through Travis CI
- [x] Set up readthedocs site

### CODE REVIEW

**Comment by mcflugen** [comment]
@mdpiper I've added a docs build stage to the Travis CI that builds the docs and set up a [readthedocs](https://babelizer.readthedocs.io/en/mdpiper-make-docs/) site.

**Comment by mcflugen** [comment]
@mdpiper I've added a few sections based on top-level docs (e.g. *authors*, *changelog*, etc.) and brought the contents of the *readme* file into the docs.

**Comment by mdpiper** [comment]
@mcflugen Thank you!

**Comment by mdpiper** [comment]
@mcflugen I'd like to make a long-form example of wrapping bmi-example-c. Should it go in the README (in *Examples*), or in a separate file?

It would make the README kinda long.

**Comment by mcflugen** [comment]
@mdpiper Probably in a separate document. The README is, as you say, already on the long side and is only intended to give a quick overview anyway.

**Pull request merged**
