### PR TITLE
Add noxfile and remove lint

### PR DESCRIPTION
**Pull request by mcflugen**
I've added a *nox* file for running routine maintenance tasks like building the docs, running the tests, building the examples, checking for lint, etc. I've also changed to using *pre-commit* to run the linters and check for much more lint than before (I've removed all of the newly found lint). The ci tests have been simplified to use *nox*.

Other things included in this pull request,
* Combined all of our linters (including *black*) into a single workflow that runs `nox -s lint`
* Dropped Python 3.8 but haven't added 3.11 yet
* Updated the *readthedocs* config file as it was way out of date
* In the template *pyproject.toml* file, require *setuptools<60*. This is necessary when building fortran extensions because *numpy* has dropped support of distutils and are in the process of switching the Meson
* Switched from a mix of Google and *numpy* style docstrings to  just *numpy* syle. It's what we use everywhere else.
* Removed the deprecated *wrap.py* module.
* I cleaned up the language tests but, in the end, I've moved the language testing into the *nox* file. I think it's easier to read there and is less spaghetti like.

### CODE REVIEW

**Comment by mcflugen** [comment]
@mdpiper When you have a chance would you please have a look at this pull request. Thanks!

In case you're interested, the docs are building on [rtfd](https://babelizer.readthedocs.io/en/mcflugen-add-noxfile-remove-lint/).

**Review by mdpiper — APPROVED** [review]
Would you like to polish this off by removing the `Makefile`?

**Comment by mdpiper** [comment]
A minor issue I can work around, but I want to mention it just in case I'm missing something.

In building the C example:
```
$ nox -s "build-examples(lang='c')"
```
it doesn't like the `mamba` backend:
```
ValueError: Expected venv_backend one of ('virtualenv', 'conda', 'venv'), but got 'mamba'.
```

I can edit the noxfile to use `conda` instead.

**Comment by mcflugen** [comment]
@mdpiper That's weird. What version of *nox* to you have? I assume you have *mamba* installed?

You don't need to modify the *noxfile* to change the backend. The following should override the backend declared in the *noxfile*,
```bash
nox --force-venv-backend=conda -s "build-examples(lang='c')"
```

**Pull request merged**
