### PR TITLE
Build babelized projects with meson

### LINKED ISSUE #77: Find new build process for Fortran libraries
The *babelizer* uses *numpy.distutils* to build Fortran libraries. In Python 3.10, *numpy.distutils* has been [deprecated](https://peps.python.org/pep-0632/) in favor of *setuptools*, and it will be removed entirely in Python 3.12. While *setuptools* has incorporated much of *numpy.distutils*, it's [not a complete replacement](https://numpy.org/doc/stable/reference/distutils_status_migration.html). Significantly, it will not include [Fortran build support](https://numpy.org/doc/stable/reference/distutils_status_migration.html#moving-to-setuptools).

We need to find a new way to build Fortran libraries through the *babelizer*.

### LINKED ISSUE #87: Use Meson to build all babelized projects
Currently, we use setuptools (C, C++, Python) and numpy.distutils (Fortran) to build babelized projects. With numpy.distutils being removed in Python 3.12, we need a different build system for Fortran projects (see #77). [Meson](https://mesonbuild.com/), along with [meson-python](https://meson-python.readthedocs.io/en/latest/), was [suggested](https://numpy.org/doc/stable/reference/distutils_status_migration.html#migration-advice) as an alternative.

To keep things as simple as possible in the babelizer, it would be ideal to use the same build system for all babelized projects. Meson (and meson-python) can build C, C++, Fortran, Python, and Java projects, using a configuration file that can be templated.

### PR DESCRIPTION
**Pull request by mdpiper**
This PR changes the build system for babelized projects from *setuptools* to *meson*.

This fixes #77 and fixes #87.

### CODE REVIEW

**Comment by mdpiper** [comment]
I'm starting with Fortran, then I'll generalize to the other supported languages.

**Comment by mcflugen** [comment]
@mdpiper We're getting close, I think. Some things we still need to do,
* [x] Remove unnecessary files. Some files I think that can be removed from the template are *Makefile*, *setup.py*, and *setup_utils.py*.
* [x] *meson.build* should probably be removed when creating a pure-python package since, in that case, we use *setuptools*, not *meson*.

I'm sure there are other things but I just wanted to get these down before I forget about them.

**Comment by mdpiper** [comment]
@mcflugen I'll remove the *Makefile*. Should I also remove *MANIFEST.in* from the template?

**Comment by mcflugen** [comment]
> Should I also remove MANIFEST.in from the template?

Yes, but we'll have to make sure that everything is included in the source distribution that needs to be (the only extra stuff is the *data* folder, I think).

Maybe something along the lines of,
```toml
[tool.setuptools.package-data]
package_name = [
    "data/component_1/*",
    "data/component_2/*",
]
```

**Comment by mdpiper** [comment]
I'll leave the `MANIFEST.in` file for now since addressing it veers away from the main point of this PR.

I will update the README, though, because if a user does an editable install with *pip*, they need to set `--no-build-isolation`. (This is *meson-python* [behavior](https://meson-python.readthedocs.io/en/latest/how-to-guides/editable-installs.html).)

**Comment by mdpiper** [comment]
@mcflugen I think this is ready to go. What do you think?

**Review by mcflugen — APPROVED** [review]
👍

**Pull request merged**
