### PR TITLE
Merge cookiecutter into the babelizer

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request is an attempt to merge the *cookiecutter-bmi-wrap* repository into the *bmi_wrap* package (soon to be renamed *babelizer*).

### CODE REVIEW

**Comment by mdpiper** [comment]
@mcflugen I'm not sure this pulled in some recent changes to the cookiecutter--I had some commits from earlier this year.

**Comment by mcflugen** [comment]
@mdpiper Ah, yes, you are quite right. In trying to figure out the best way to merge the repositories I forgot to update my copy of the cookiecutter.

**Comment by mdpiper** [comment]
@mcflugen Ah, OK. Are you trying `git subtree`? I experimented with it earlier this morning.

**Comment by mcflugen** [comment]
@mdpiper I think this should now include your changes. Could you have a look to see that everything is there that you think should be there?

**Comment by mdpiper** [comment]
@mcflugen Yup, no diffs! Thank you.

**Pull request merged**
