### PR TITLE
Add text describing similar work

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds text about how others have previously dealt with language interoperability. In particular, The Common Component Architecture (through *babel*) and *eWaterCycle* (through *grpc4BMI*).

### CODE REVIEW

**Comment by mdpiper** [comment]
@mcflugen We use `babelizer` and *babel* in the paper. Should we use the same formatting style for each?

**Comment by mcflugen** [comment]
@mdpiper Yes, I think we should. I vote for *babelizer*.

**Comment by mdpiper** [comment]
@mcflugen I'll make it so.

**Comment by mdpiper** [comment]
@mcflugen I looked over the preview and we're 🚀 .

**Pull request merged**
